enforce usage of cpip environment, and throw error otherwise

diff --git a/bin/cpip b/bin/cpip
--- a/bin/cpip
+++ b/bin/cpip
@@ -114,6 +114,10 @@ env="cpip_env"
 
 conda_initiate()
 {
+    if [[ $CONDA_DEFAULT_ENV != "cpip" ]]; then
+        echo "$error" "cpip environment must be active! please run 'conda activate cpip' prior to use"
+        exit 1
+    fi
     source "$CONDA_PREFIX/etc/profile.d/conda.sh"
     conda activate
 }
