no-color option

diff --git a/cpip b/cpip
--- a/cpip
+++ b/cpip
@@ -9,18 +9,35 @@ set_script_space()
 }
 set_script_space
 
-# set colors
-bold=`tput bold`
-red=`tput setaf 1`
-green=`tput setaf 2`
-yellow=`tput setaf 3`
-blue=`tput setaf 4`
-magenta=`tput setaf 5`
-cyan=`tput setaf 6`
-reset=`tput sgr0`
+set_colors()
+{
+    bold=`tput bold`
+    red=`tput setaf 1`
+    green=`tput setaf 2`
+    yellow=`tput setaf 3`
+    blue=`tput setaf 4`
+    magenta=`tput setaf 5`
+    cyan=`tput setaf 6`
+    reset=`tput sgr0`
+}
+
+min_args=0
+for arg in $@; do
+    if [[ $arg == "--no-color" ]]; then
+        no_color=true
+        ((++min_args))
+    fi
+done
+if [[ $no_color ]]; then
+    export PIP_NO_COLOR=1
+    no_ansi="--no-ansi"
+else
+    ansi="--ansi"
+    set_colors
+fi
 
 # set print commands
-default_tag="${bold}${magenta}[${cyan}$script_name${magenta}]$reset"
+default_tag="${bold}${magenta}[${cyan}$script_name${magenta}]${reset}"
 
 # store empty string equivalent of 'info' and 'help'
 four_space="[$script_name] FOUR:"
@@ -112,33 +129,40 @@ usage()
     echo "$s___" "  clean                     Cleanup conda and/or pip cache."
     echo "$s___"
     echo "$s___" "options:"
+    echo "$s___" "  --no-color                Disable colored output."
     echo "$s___" "  --help, -h                Show this help message then exit."
 }
 
-if [[ $# -eq 0 ]]; then
+if [[ $# -le $min_args ]]; then
     usage
     exit 0
 fi
 
-case $1 in
-    pack)
-        script_name+=" $1"
-        set_script_space
-        shift
-        source "$script_dir/cpip-pack"
-        ;;
-    clean)
-        script_name+=" $1"
-        set_script_space
-        shift
-        source "$script_dir/cpip-clean"
-        ;;
-    -h|--help)
-        usage
-        ;;
-    *)
-        echo "$error" "'$1' not a recognized command"
-        usage
-        exit 1
-        ;;
-esac
+while [[ $# -gt 0 ]]; do
+    case $1 in
+        pack)
+            script_name+=" $1"
+            set_script_space
+            shift # past argument
+            source "$script_dir/cpip-pack"
+            ;;
+        clean)
+            script_name+=" $1"
+            set_script_space
+            shift # past argument
+            source "$script_dir/cpip-clean"
+            ;;
+        --no-color)
+            shift # past argument
+            ;;
+        -h|--help)
+            usage
+            exit 0
+            ;;
+        *)
+            echo "$error" "'$1' not a recognized command"
+            usage
+            exit 1
+            ;;
+    esac
+done
diff --git a/cpip-clean b/cpip-clean
--- a/cpip-clean
+++ b/cpip-clean
@@ -18,17 +18,13 @@ usage()
     echo "$s___" "  --pip-cache, -p           Remove cpip's pip cache."
     echo "$s___"
     echo "$s___" "options:"
-    echo "$s___" "  --yes, -y                 Consent to deletion without prompts."
+    echo "$s___" "  --yes                     Consent to deletion without prompts."
+    echo "$s___" "  --no-color                Disable colored output."
     echo "$s___" "  --quiet, -q               Suppress output for commands."
     echo "$s___" "  --help, -h                Show this help message then exit."
 }
 
-if [[ $# -eq 0 ]]; then
-    echo "$error" "at least one argument is required"
-    usage
-    exit 1
-fi
-
+arg_count=0
 while [[ $# -gt 0 ]]; do
     case $1 in
         -s|--slip)
@@ -38,6 +34,7 @@ while [[ $# -gt 0 ]]; do
                 exit 1
             fi
             slip="$1"
+            ((++arg_count))
             shift # past argument
             ;;
         -t|--tarballs)
@@ -47,6 +44,7 @@ while [[ $# -gt 0 ]]; do
                 exit 1
             fi
             tarballs="$1"
+            ((++arg_count))
             shift # past argument
             ;;
         -p|--pip-cache)
@@ -56,15 +54,19 @@ while [[ $# -gt 0 ]]; do
                 exit 1
             fi
             pip_cache="$1"
+            ((++arg_count))
             shift # past argument
             ;;
-        -y|--yes)
+        --yes)
             if [[ $yes ]]; then
                 echo "$error" "'--yes' option cannot be used more than once"
                 usage
                 exit 1
             fi
             yes="$1"
+            shift # past argument
+            ;;
+        --no-color)
             shift # past argument
             ;;
         -q|--quiet)
@@ -88,6 +90,12 @@ while [[ $# -gt 0 ]]; do
             ;;
     esac
 done
+
+if [[ $arg_count -eq 0 ]]; then
+    echo "$error" "at least one argument is required"
+    usage
+    exit 1
+fi
 
 # exit as soon as a command fails and print error
 trap exit_trap EXIT
