added more intuitive version tagging

diff --git a/src/cpip-pack b/src/cpip-pack
--- a/src/cpip-pack
+++ b/src/cpip-pack
@@ -160,47 +160,54 @@ exit_trap()
 complete_msg()
 {
     if [[ $poetry_dir ]]; then
-        local poetry_lockfile="$output_name/$dep_name/$poetry_lock"
+        local poetry_lockfile="$name/$dep_name/$poetry_lock"
     else
         local poetry_lockfile="NOT_APPLICABLE"
     fi
 
     # NOTE: if you update this print message, please update README.md
-    echo     "$info" "Complete! Environment is now installed in '$output'"
-    echo     "$help" "[Instructions]"
-    echo     "$____"
     if [[ $create ]]; then
+        echo "$info" "Complete! Environment is now installed in '$output'"
+        echo "$help" "[Instructions]"
+        echo "$____"
         echo "$____" "  Normal Use:"
         echo "$____" "    *  activate             --> source $output/bin/activate"
         echo "$____" "    *  deactivate           --> source deactivate"
         echo "$____"
         echo "$____" "  If in 'envs' folder:"
-        echo "$____" "    *  activate             --> conda activate $output_name"
+        echo "$____" "    *  activate             --> conda activate $name"
         echo "$____" "    *  deactivate           --> conda deactivate"
     else
+        echo "$info" "Complete! Environment is now packaged at '$output'"
+        echo "$help" "[Instructions]"
+        echo "$____"
         echo "$____" "  Initial Setup:"
         echo "$____" "    1. untar archive        --> tar -xf $output_file"
-        echo "$____" "    2. activate environment --> source $output_name/bin/activate"
+        echo "$____" "    2. activate environment --> source $name/bin/activate"
         echo "$____" "    3. fix path prefixes    --> conda unpack"
         echo "$____"
         echo "$____" "  Normal Use:"
-        echo "$____" "    *  activate             --> source $output_name/bin/activate"
+        echo "$____" "    *  activate             --> source $name/bin/activate"
         echo "$____" "    *  deactivate           --> source deactivate"
     fi
     echo     "$____"
     echo     "$____" "  Info:"
-    echo     "$____" "    *  conda dependencies     @ $output_name/$dep_name/$dep_file"
+    echo     "$____" "    *  conda dependencies     @ $name/$dep_name/$dep_file"
     echo     "$____" "    *  poetry lockfile        @ $poetry_lockfile"
 }
 
 usage()
 {
     # NOTE: if you update this print message, please update README.md
-    echo "$help" "usage: $script_name --name PROJECT [--file FILE]..."
-    echo "$____" "       $___________ [--poetry DIR] [--version VERSION] [--output DIR]"
-    echo "$____" "       $___________ [--post-setup SCRIPT] [--no-dev] [--unlock]"
-    echo "$____" "       $___________ [--force] [--color] [--no-color] [--quiet]"
-    echo "$____" "       $___________ [--help]"
+    echo     "$help" "usage: $script_name --name PROJECT [--file FILE]..."
+    if [[ $create ]]; then
+        echo "$____" "       $___________ [--poetry DIR] [--output DIR]"
+    else
+        echo "$____" "       $___________ [--poetry DIR] [--version VERSION] [--output DIR]"
+    fi
+    echo     "$____" "       $___________ [--post-setup SCRIPT] [--no-dev] [--unlock]"
+    echo     "$____" "       $___________ [--force] [--color] [--no-color] [--quiet]"
+    echo     "$____" "       $___________ [--help]"
 }
 
 advanced_usage()
@@ -208,7 +215,7 @@ advanced_usage()
     
     # NOTE: if you update this print message, please update README.md
     usage
-    echo "$____"
+    echo     "$____"
     if [[ $create ]]; then
         local output="folder"
         echo "$____" "Create a conda environment from the given dependencies"
@@ -216,30 +223,32 @@ advanced_usage()
         local output="tarball"
         echo "$____" "Package all dependencies into a portable conda environment tarball"
     fi
-    echo "$____"
+    echo     "$____"
     
-    echo "$____" "required arguments:"
-    echo "$____" "  --name, -n PROJECT        Name of the project. Will be used for the name in"
-    echo "$____" "                            the output $output."
-    echo "$____"
-    echo "$____" "optional arguments:"
-    echo "$____" "  --file, -f FILE           Conda environment file. This option can be used"
-    echo "$____" "                            multiple times to specify multiple files. The"
-    echo "$____" "                            environment will be updated in the order that they"
-    echo "$____" "                            are given on the command line."
-    echo "$____" "  --poetry, -p DIR          Poetry project directory."
-    echo "$____" "  --version, -v VERSION     Version number to be included in output $output."
-    echo "$____" "  --output, -o DIR          Directory where the final $output will go."
-    echo "$____" "                            Otherwise, $output will be ouputed to the current"
-    echo "$____" "                            working directory."
-    echo "$____" "  --post-setup SCRIPT       Script to run after the environment is setup."
-    echo "$____" "  --no-dev                  Do not install dev dependencies for Poetry."
-    echo "$____" "  --unlock                  Update Poetry dependencies and overwrite lockfile."
-    echo "$____" "  --force                   Overwrite any existing $output at the output path."
-    echo "$____" "  --color                   Force colored output."
-    echo "$____" "  --no-color                Disable colored output."
-    echo "$____" "  --quiet, -q               Suppress output for commands."
-    echo "$____" "  --help, -h                Show this help message then exit."
+    echo     "$____" "required arguments:"
+    echo     "$____" "  --name, -n PROJECT        Name of the project. Will be used for the name in"
+    echo     "$____" "                            the output $output."
+    echo     "$____"
+    echo     "$____" "optional arguments:"
+    echo     "$____" "  --file, -f FILE           Conda environment file. This option can be used"
+    echo     "$____" "                            multiple times to specify multiple files. The"
+    echo     "$____" "                            environment will be updated in the order that they"
+    echo     "$____" "                            are given on the command line."
+    echo     "$____" "  --poetry, -p DIR          Poetry project directory."
+    if [[ -z $create ]]; then
+        echo "$____" "  --version, -v VERSION     Version number to be included in output $output."
+    fi
+    echo     "$____" "  --output, -o DIR          Directory where the final $output will go."
+    echo     "$____" "                            Otherwise, $output will be ouputed to the current"
+    echo     "$____" "                            working directory."
+    echo     "$____" "  --post-setup SCRIPT       Script to run after the environment is setup."
+    echo     "$____" "  --no-dev                  Do not install dev dependencies for Poetry."
+    echo     "$____" "  --unlock                  Update Poetry dependencies and overwrite lockfile."
+    echo     "$____" "  --force                   Overwrite any existing $output at the output path."
+    echo     "$____" "  --color                   Force colored output."
+    echo     "$____" "  --no-color                Disable colored output."
+    echo     "$____" "  --quiet, -q               Suppress output for commands."
+    echo     "$____" "  --help, -h                Show this help message then exit."
 }
 
 opt_twice_err()
@@ -350,15 +359,6 @@ for file in ${files[@]}; do
     fi
 done
 
-# set output file env
-output_name="$name"
-if [[ $version ]]; then
-    if [[ ! $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then 
-        >&2 echo "$warning" "'$version' does not match numerical format X.Y.Z"
-    fi 
-    output_name+="-$version"
-fi
-
 # set full output path
 if [[ -z $output_dir ]]; then
     output_dir="$(pwd)"
@@ -367,10 +367,19 @@ if [[ ! -d $output_dir ]]; then
     >&2 echo "$error" "'$output_dir' is not a directory or does not exist"
     exit 1
 fi
+
+# set other output variables
 output_dir="$(readlink -e "$output_dir")"  # <-- set to absolute path
 if [[ $create ]]; then 
-    output="$output_dir/$output_name"
+    output="$output_dir/$name"
 else
+    output_name="$name"
+    if [[ $version ]]; then
+        if [[ ! $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            >&2 echo "$warning" "'$version' does not match numerical format X.Y.Z"
+        fi
+        output_name+="-$version"
+    fi
     output_file="$output_name.tar.gz"
     output="$output_dir/$output_file"
 fi
@@ -454,7 +463,7 @@ done
 # setup dependencies info output
 dep_name="dependencies"
 dep_dir="$CONDA_PREFIX/$dep_name"
-dep_file="$output_name.yml"
+dep_file="$name.yml"
 poetry_lock="poetry.lock"
 mkdir -p "$dep_dir"
 
@@ -517,7 +526,7 @@ conda env export | grep -v "^prefix: " | grep -v "^$" > "$dep_dir/$dep_file"
 if [[ $create ]]; then
     echo "$info" "packaging environment via conda-pack..."
     make_temp
-    conda pack -o "$temp_file" -d "$output" --arcroot "$output_name" --compress-level 0 $force $quiet $log_quiet
+    conda pack -o "$temp_file" -d "$output" --arcroot "$name" --compress-level 0 $force $quiet $log_quiet
     cd "$output_dir"
     echo "$info" "unpacking environment..."
     [[ $force ]] && rm -rf "$output"
@@ -526,7 +535,7 @@ if [[ $create ]]; then
     cd -
 else
     echo "$info" "packaging environment via conda-pack..."
-    conda pack -o "$output" --arcroot "$output_name" $force $quiet $log_quiet
+    conda pack -o "$output" --arcroot "$name" $force $quiet $log_quiet
 fi
 
 complete_msg
